### ISSUE TITLE
fn will still execute one more even after instance.stop()

### ISSUE THREAD

**Issue by glyphgitjembo** [lionralfs/precurring#12]
https://github.com/lionralfs/precurring/blob/d02f7b2743a391ed72c9a74afdb8c6c7b7167e3a/src/index.js#L71-L84

`instance.stop()` will only assign the value for `running` to `false`. `wait` function will still be executed thus running the function again even though its result will not be honored since `running` will be checked. Problem arises when `fn` does writing or updating.

I think the `wait(interval).then(run)` should be enclosed in another `if (running)` for both `onSuccess` and `onError`

**Comment by lionralfs** [comment]
Hey, thanks for the catch. I went ahead and fixed it in v1.0.3. Feel free to test it out and let me know if you have any other issues.
